import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedRaffleKeys1574028210607 implements MigrationInterface {
    name = 'AutoGeneratedRaffleKeys1574028210607'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_10d384c844b7c32214cbe50cc7"`, undefined);
        await queryRunner.query(`ALTER TABLE "Raffle" DROP COLUMN "joinKey"`, undefined);
        await queryRunner.query(`ALTER TABLE "Raffle" ADD "joinKey" uuid NOT NULL DEFAULT uuid_generate_v4()`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8816b9d39130982c2f4035a8e5" ON "Raffle" ("joinKey") `, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_8816b9d39130982c2f4035a8e5"`, undefined);
        await queryRunner.query(`ALTER TABLE "Raffle" DROP COLUMN "joinKey"`, undefined);
        await queryRunner.query(`ALTER TABLE "Raffle" ADD "joinKey" character varying(50) NOT NULL`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_10d384c844b7c32214cbe50cc7" ON "Raffle" ("name") `, undefined);
    }

}
